apiVersion: apps/v1
kind: Deployment
metadata:
  name: therapieland-deployment
  namespace: therapieland
  labels:
    app: therapieland-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: therapieland-app
  template:
    metadata:
      labels:
        app: therapieland-app
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/arch
                operator: In
                values:
                - amd64
                - arm64
      containers:
      - name: nginx
        image: sbeuran/therapieland-assignment
        ports:
        - name: http
          containerPort: 8080
        imagePullPolicy: IfNotPresent
      nodeSelector:
        kubernetes.io/os: linux