apiVersion: apps/v1
kind: Deployment
metadata:
  name: therapieland-deployment
  namespace: therapieland
  labels:
    app: therapieland-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: therapieland-app
  template:
    metadata:
      labels:
        app: therapieland-app
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/arch
                operator: In
                values:
                - amd64
                - arm64
      containers:
      - name: therapieland-app
        image: sbeuran/therapieland-assignment
        env:
          - name: DB_HOST
            valueFrom:
              secretKeyRef:
                name: therapieland-secret
                key: DB_HOST
          - name: DB_NAME
            valueFrom:
              secretKeyRef:
                name: therapieland-secret
                key: DB_NAME
          - name: DB_PASS
            valueFrom:
              secretKeyRef:
                name: therapieland-secret
                key: DB_PASS
          - name: DB_USER
            valueFrom:
              secretKeyRef:
                name: therapieland-secret
                key: DB_USER
        ports:
        - name: http
          containerPort: 8080
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        imagePullPolicy: IfNotPresent
      nodeSelector:
        kubernetes.io/os: linux