name: Docker Image CI

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Build the Docker image
      run: cd custom-http-server; docker build . --tag sbeuran/therapieland-assignment:latest; cd ..;
    
    - name: Login to dockerhub registry
      run: echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login --username "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin
    
    - name: Push the Docker image
      run: docker push sbeuran/therapieland-assignment:latest

  deploy:
    needs: build

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Install Gcloud plugins
      run: |
        curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo gpg --dearmor -o /usr/share/keyrings/cloud.google.gpg
        echo "deb [signed-by=/usr/share/keyrings/cloud.google.gpg] https://packages.cloud.google.com/apt cloud-sdk main" | sudo tee -a /etc/apt/sources.list.d/google-cloud-sdk.list
        sudo apt-get update
        sudo apt-get install google-cloud-sdk-gke-gcloud-auth-plugin

    - name: Setup kubectl
      run: |
        curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
        chmod 700 ./kubectl

    - name: Save kubeconfig and set it as default
      run: |

    - name: Deploy to K8S
      env:
        GCLOUD_SA_KEY_JSON: ${{ secrets.GCLOUD_SA_KEY_JSON }}
        KUBECONFIG_DATA: ${{ secrets.KUBECONFIG_DATA }}
        DB_HOST: ${{ secrets.DB_HOST }}
        DB_NAME: ${{ secrets.DB_NAME }}
        DB_PASS: ${{ secrets.DB_PASS }}
        DB_USER: ${{ secrets.DB_USER }}
      run: |
        echo "$GCLOUD_SA_KEY_JSON" > ./gcloud.key.json
        gcloud auth activate-service-account --key-file=gcloud.key.json

        echo "$KUBECONFIG_DATA" > ./kubeconfig
        export KUBECONFIG=./kubeconfig
        
        ./kubectl delete namespace therapieland --ignore-not-found=true
        ./kubectl create namespace therapieland

        ./kubectl create secret generic therapieland-secret -n therapieland \
          --from-literal=DB_HOST=$DB_HOST \
          --from-literal=DB_NAME=$DB_NAME \
          --from-literal=DB_PASS=$DB_PASS \
          --from-literal=DB_USER=$DB_USER 

        ./kubectl apply -f k8s/deployment.yaml
        ./kubectl apply -f k8s/service.yaml
        ./kubectl apply -f k8s/hpa.yaml